// <auto-generated />
using System;
using CityBreaks.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityBreaks.Web.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250606005417_AddDeletedAtToProperty")]
    partial class AddDeletedAtToProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Vancouver"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "London"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 4,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 5,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 6,
                            Name = "Rio de Janeiro"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "US",
                            CountryName = "United States"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "CA",
                            CountryName = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "GB",
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "FR",
                            CountryName = "France"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "DE",
                            CountryName = "Germany"
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "BR",
                            CountryName = "Brazil"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT")
                        .HasColumnName("PricePerNight");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Central Park Hotel",
                            PricePerNight = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Hollywood Inn",
                            PricePerNight = 120.00m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Downtown Toronto Suites",
                            PricePerNight = 180.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Vancouver Bay Hotel",
                            PricePerNight = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Name = "London Eye Apartments",
                            PricePerNight = 250.00m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Name = "Parisian Charm Hotel",
                            PricePerNight = 300.00m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Name = "Berlin Central Hostel",
                            PricePerNight = 80.00m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 8,
                            Name = "Rio Beach Resort",
                            PricePerNight = 220.00m
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Property", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
